Repository 6im0n/Arcade, pull requests merged in 2024-04, with the labels that each got.

#67 🚧 Refactor Makefile and update file paths
  Makefile
Labels: bug, Architecture

#75 make sfml implementation
  Makefile
  assets/core/Roboto-Regular.ttf
  assets/core/button.png
  assets/core/buttonSelect.png
  core/Core.cpp
  core/menu/Button.cpp
  core/menu/Button.hpp
  core/menu/Menu.cpp
  core/menu/Menu.hpp
  lib/topScores.txt
  src/sfml/Sfml.cpp
  src/sfml/Sfml.hpp
  src/sfml/sfml.cpp
  src/snake/Entities/Food.cpp
  src/snake/Entities/SnakeBody.cpp
  src/snake/Entities/Void.cpp
  src/snake/Entities/Wall.cpp
  tests/snake/Entities/tests_food.cpp
  tests/snake/Entities/tests_snake_body.cpp
  tests/snake/Entities/tests_void.cpp
  tests/snake/Entities/tests_wall.cpp
Labels: enhancement, GraphicsLib

#77 71 fix grow snake
  src/snake/Entities/SnakeBody.cpp
  src/snake/Entities/SnakeBody.hpp
  src/snake/Snake.cpp
  src/snake/Snake.hpp
  src/snake/direction.hpp
  tests/snake/Entities/tests_snake_body.cpp
Labels: bug, games, snake

#84 ✨ Add all entities for centipede game
  Makefile
  core/menu/Menu.hpp
  src/centipede/CentipedeGame.cpp
  src/centipede/CentipedeGame.hpp
  src/centipede/Entities/Bullet.cpp
  src/centipede/Entities/Bullet.hpp
  src/centipede/Entities/Player.cpp
  src/centipede/Entities/Player.hpp
  src/centipede/Entities/SnakeBody.cpp
  src/centipede/Entities/SnakeBody.hpp
  src/centipede/Entities/Void.cpp
  src/centipede/Entities/Void.hpp
  src/centipede/Entities/VoidRunnable.cpp
  src/centipede/Entities/VoidRunnable.hpp
  src/centipede/Entities/Wall.cpp
  src/centipede/Entities/Wall.hpp
  src/centipede/Score.cpp
  src/centipede/Score.hpp
  src/centipede/Snake.cpp
  src/centipede/Snake.hpp
  src/pacman/pacman.cpp
Labels: games, centipede

#82 📝 Update the readme to add the email of the group leader for shared i…
  README.md
Labels: documentation

#87 83 core lib getter
  core/Core.cpp
  core/Core.hpp
  core/DLLoader.cpp
  core/DLLoader.hpp
  core/menu/Menu.cpp
  core/menu/Menu.hpp
  src/pacman/pacman.cpp
  src/pacman/pacman.hpp
  src/sdl/sdl.cpp
  src/sdl/sdl.hpp
Labels: enhancement

#89 56 make sdl2 implementation
  Makefile
  classes/Text.cpp
  classes/Text.hpp
  core/menu/Menu.cpp
  src/pacman/pacman.cpp
  src/pacman/pacman.hpp
  src/sdl/Sdl.cpp
  src/sdl/Sdl.hpp
  src/sdl/sdl.cpp
  src/sdl/sdl.hpp
  src/sfml/Sfml.cpp
  src/snake/Entities/Food.cpp
  src/snake/Entities/SnakeBody.cpp
  src/snake/Entities/Void.cpp
  src/snake/Entities/Wall.cpp
  tests/snake/Entities/tests_food.cpp
  tests/snake/Entities/tests_snake_body.cpp
  tests/snake/Entities/tests_void.cpp
  tests/snake/Entities/tests_wall.cpp
Labels: enhancement, GraphicsLib

#91 57 make ncurse implementation
  Makefile
  abstract/AGame.hpp
  classes/Color.hpp
  classes/Text.hpp
  src/ncurses/Ncurses.cpp
  src/ncurses/Ncurses.hpp
  src/ncurses/ncurses.cpp
  src/pacman/pacman.cpp
  src/pacman/pacman.hpp
  src/sdl/Sdl.hpp
  src/snake/Entities/Food.cpp
  src/snake/Entities/Food.hpp
  src/snake/Entities/SnakeBody.cpp
  src/snake/Entities/SnakeBody.hpp
  src/snake/Entities/Void.hpp
  src/snake/Entities/Wall.hpp
  src/snake/Score.hpp
  src/snake/SnakeGame.hpp
  tests/snake/Entities/tests_food.cpp
  tests/snake/Entities/tests_snake_body.cpp
Labels: enhancement, GraphicsLib

#94 🐛 fix change the graphic lib
  core/Core.cpp
  core/menu/Menu.cpp
Labels: enhancement, GraphicsLib

#97 🐛 snake back movement
  src/snake/Snake.cpp
Labels: bug, games, snake

#95 78 create centipede game
  Makefile
  includes/Direction.hpp
  src/centipede/CentipedeGame.cpp
  src/centipede/CentipedeGame.hpp
  src/centipede/Entities/Bullet.cpp
  src/centipede/Entities/Bullet.hpp
  src/centipede/Entities/Player.cpp
  src/centipede/Entities/Player.hpp
  src/centipede/Entities/SnakeBody.cpp
  src/centipede/Entities/SnakeBody.hpp
  src/centipede/Entities/Void.cpp
  src/centipede/Entities/Void.hpp
  src/centipede/Entities/Wall.cpp
  src/centipede/Entities/Wall.hpp
  src/centipede/Score.cpp
  src/centipede/Score.hpp
  src/centipede/Snake.cpp
  src/centipede/Snake.hpp
  src/pacman/pacman.cpp
  src/snake/Entities/SnakeBody.hpp
  src/snake/Snake.hpp
  tests/snake/Entities/tests_snake_body.cpp
Labels: games, centipede

#100 99 fix lag in snake game
  src/pacman/pacman.hpp
  src/snake/SnakeGame.cpp
Labels: bug, games, snake

#106 ✨ add random wall in centipede map
  src/centipede/CentipedeGame.cpp
Labels: games, centipede

#102 🐛 add username in Game libs
  Interfaces/IGame.hpp
  Makefile
  abstract/AGame.cpp
  abstract/AGame.hpp
  src/centipede/CentipedeGame.cpp
  src/centipede/CentipedeGame.hpp
  src/snake/SnakeGame.cpp
  src/snake/SnakeGame.hpp
Labels: bug, games

#107 🐛 position of the bullet
  src/centipede/Entities/Player.cpp
Labels: games, centipede
